# Site settings
title: Hongwen Blog
SEOTitle: Hongwen's blog | HW Blog
header-img: img/home-bg-pic.jpg
email: hit_master@163.com
description: "不积跬步无以至千里"
keyword: "HW, HW Blog, 洪文的博客, 孙洪文, sunhongwen, AI, ASRT, kaldi"
url: "http://audier.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/audier/audier.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "海阔凭鱼跃，天高任鸟飞"
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     sunhongwen
github_username:    audier
#facebook_username:  baiying.qiu.7
jianshu_username:   chinatelecom08
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  math_engine: mathjax
  syntax_highlighter: rouge


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    
  clientID: d210871bea579a760769                            
  clientSecret: a9609b36817032c93aaa4401ce61755a796c78d6 
  repo: audier.github.io    
  owner: audier    
  admin: audier
  distractionFreeMode: true 


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "MY CSDN",
        href: "https://blog.csdn.net/chinatelecom08"
    },{
        title: "GITHUB",
        href: "https://github.com/audier"
    }
]
